// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {MonadVRFVerifier} from "../../src/contracts/MonadVRFVerifier.sol";
import {MonadVRFAdapter} from "../../src/contracts/MonadVRFAdapter.sol";
import {MockConsumer, MockGriefer, MockReverter, MockReturnBomb} from "./MockConsumer.sol";

// Proof generated by: npx tsx scripts/genProof.ts
// k = 42, roundId = bytes32("round-1"), hash-to-curve via RFC 9380 (@noble/curves)
// Note: gamma/c/s depend only on roundId and k, NOT on the requesting consumer,
// so the same fixture works for any consumer that requests this roundId.

contract MonadVRFAdapterTest is Test {
    MonadVRFVerifier verifier;
    MonadVRFAdapter adapter;
    MockConsumer consumer;

    // Allow this test contract to receive fee payments when it acts as the fulfiller.
    receive() external payable {}

    bytes32 constant ROUND_ID = bytes32("round-1");
    uint256 constant REQUEST_FEE = 0.001 ether;

    // EIP-2537 128-byte oracle public key, split into 4×32-byte immutable chunks.
    bytes32 constant PK0 = 0x000000000000000000000000000000000ce3b57b791798433fd323753489cac9;
    bytes32 constant PK1 = 0xbca43b98deaafaed91f4cb010730ae1e38b186ccd37a09b8aed62ce23b699c48;
    bytes32 constant PK2 = 0x00000000000000000000000000000000008c346228e4482ec20a2bf7d5a2fe74;
    bytes32 constant PK3 = 0xebf3c79b912d1b0ba977a873b66f7a9b8b42585a78c0c21d66da6a15767efdb1;
    bytes constant PK_BYTES =
        hex"000000000000000000000000000000000ce3b57b791798433fd323753489cac9bca43b98deaafaed91f4cb010730ae1e38b186ccd37a09b8aed62ce23b699c4800000000000000000000000000000000008c346228e4482ec20a2bf7d5a2fe74ebf3c79b912d1b0ba977a873b66f7a9b8b42585a78c0c21d66da6a15767efdb1";

    bytes constant GAMMA =
        hex"000000000000000000000000000000000bb381154dc86a2b91eb3710aa412ea071e91d5122c976b0e8775474f5c5911667253293f9cdcdd05887adc908a5f4d500000000000000000000000000000000016c6b67b701a7ae42421582570c9fedef994318c7656659169985792799f39a3c2ed6b8285d6312e5179084713314da";
    uint256 constant C = 0x5973b13f00290106fe0be3dff5d921507ddb1ee0223870bb74f58fb9863f8662;
    uint256 constant S = 0x0b61101267947db0fe93d38a4cddcecb3c7988a9d4940f280ab23c1f9785ef59;
    bytes32 constant BETA = 0xcd851f1243dc4ae51c01c5688fd087556f5a1b44e65bdd4ac53408f89f513abd;

    function setUp() public {
        verifier = new MonadVRFVerifier();
        adapter = new MonadVRFAdapter(address(verifier), PK0, PK1, PK2, PK3, REQUEST_FEE);
        consumer = new MockConsumer(address(adapter));
        vm.deal(address(consumer), 10 ether);
    }

    function _fundedConsumer() internal returns (MockConsumer c) {
        c = new MockConsumer(address(adapter));
        vm.deal(address(c), 10 ether);
    }

    function _key(address c, bytes32 r) internal view returns (bytes32) {
        return adapter.requestKey(c, r);
    }

    function test_fullFlow() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        bytes32 key = _key(address(consumer), ROUND_ID);
        assertEq(adapter.pendingRequests(key), true);
        assertEq(adapter.fulfilled(key), false);

        vm.expectEmit(true, true, false, true);
        emit MonadVRFAdapter.RandomnessFulfilled(address(consumer), ROUND_ID, BETA, true);

        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);

        assertEq(consumer.lastRoundId(), ROUND_ID);
        assertEq(consumer.lastBeta(), BETA);
        assertEq(adapter.fulfilled(key), true);
        assertEq(adapter.pendingRequests(key), false);
    }

    function test_anyoneCanFulfill() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        vm.prank(address(0xdead));
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
        assertEq(consumer.lastBeta(), BETA);
    }

    function test_duplicateRequest_reverts() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyRequested.selector, address(consumer), ROUND_ID));
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
    }

    function test_requestAfterFulfill_reverts() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyFulfilled.selector, address(consumer), ROUND_ID));
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
    }

    function test_fulfillWithoutRequest_reverts() public {
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.NoPendingRequest.selector, address(consumer), ROUND_ID));
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
    }

    function test_replayFulfill_reverts() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyFulfilled.selector, address(consumer), ROUND_ID));
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
    }

    function test_invalidProof_reverts() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        vm.expectRevert(MonadVRFAdapter.InvalidProof.selector);
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C + 1, S);
    }

    // ── C1: roundId-squatting attack must not redirect the legitimate callback ──

    function test_squatCannotRedirect() public {
        // Squatter races ahead and registers the same roundId from a different address.
        MockConsumer squatter = new MockConsumer(address(adapter));
        vm.deal(address(squatter), 1 ether);
        squatter.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        // Legitimate consumer also registers - must succeed (different storage slot).
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        // Both have independent pending entries.
        assertTrue(adapter.pendingRequests(_key(address(squatter), ROUND_ID)));
        assertTrue(adapter.pendingRequests(_key(address(consumer), ROUND_ID)));

        // Fulfilling the legitimate consumer reaches the legitimate consumer only.
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
        assertEq(consumer.lastBeta(), BETA);
        assertEq(squatter.lastBeta(), bytes32(0)); // squatter received nothing

        // Squatter's separate request is still pending and independently fulfillable.
        assertTrue(adapter.pendingRequests(_key(address(squatter), ROUND_ID)));
        adapter.fulfill(address(squatter), ROUND_ID, GAMMA, C, S);
        assertEq(squatter.lastBeta(), BETA);
    }

    function test_twoConsumersSameRoundId_independentlyFulfilled() public {
        MockConsumer other = new MockConsumer(address(adapter));
        vm.deal(address(other), 1 ether);

        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        other.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        // Same proof works for both - depends on roundId only.
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);
        adapter.fulfill(address(other), ROUND_ID, GAMMA, C, S);

        assertEq(consumer.lastBeta(), BETA);
        assertEq(other.lastBeta(), BETA);

        assertTrue(adapter.fulfilled(_key(address(consumer), ROUND_ID)));
        assertTrue(adapter.fulfilled(_key(address(other), ROUND_ID)));
    }

    // ── H1: callback gas griefing must be bounded ────────────────────────────

    function test_griefingConsumer_doesNotConsumeFulfillerGas() public {
        MockGriefer griefer = new MockGriefer(address(adapter));
        vm.deal(address(griefer), 1 ether);
        griefer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        // Snapshot balances/gas around the fulfill call.
        uint256 gasBefore = gasleft();
        adapter.fulfill(address(griefer), ROUND_ID, GAMMA, C, S);
        uint256 gasUsed = gasBefore - gasleft();

        // Verifier+adapter overhead is ~180k; callback OOG burns ~CALLBACK_GAS_LIMIT
        // inside its own frame. Total bound: well under 500k. Without the cap,
        // the unbounded loop would consume ALL available gas (millions).
        assertLt(gasUsed, 500_000, "fulfill consumed too much gas under griefing callback");

        // The round still settles cleanly even though the callback OOG'd.
        assertTrue(adapter.fulfilled(_key(address(griefer), ROUND_ID)));
    }

    function test_revertingConsumer_emitsCallbackFalse_andSettles() public {
        MockReverter reverter = new MockReverter(address(adapter));
        vm.deal(address(reverter), 1 ether);
        reverter.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        vm.expectEmit(true, true, false, true);
        emit MonadVRFAdapter.RandomnessFulfilled(address(reverter), ROUND_ID, BETA, false);

        adapter.fulfill(address(reverter), ROUND_ID, GAMMA, C, S);

        // Callback failed silently; round is still marked fulfilled (no retry path).
        // Off-chain monitors detect the failure via callbackOk=false in the event.
        assertTrue(adapter.fulfilled(_key(address(reverter), ROUND_ID)));
        assertEq(reverter.lastBeta(), bytes32(0)); // never received the value
    }

    function test_returnBomb_doesNotInflateFulfillerGas() public {
        MockReturnBomb bomb = new MockReturnBomb(address(adapter));
        vm.deal(address(bomb), 1 ether);
        bomb.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        uint256 gasBefore = gasleft();
        adapter.fulfill(address(bomb), ROUND_ID, GAMMA, C, S);
        uint256 gasUsed = gasBefore - gasleft();

        // 64 KB of returndata copied via returndatacopy would cost ~24k extra
        // (3 gas per word × 2048 words) plus memory expansion (quadratic).
        // With (0,0) output buffer in the assembly call, no copy happens.
        // Without the assembly fix this test typically blows past 600k.
        assertLt(gasUsed, 500_000, "return-bomb inflated fulfill gas");
        assertTrue(adapter.fulfilled(_key(address(bomb), ROUND_ID)));
    }

    // ── H3: fee enforcement, escrow, fulfiller payment ──────────────────────

    function test_underpayment_reverts() public {
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.IncorrectFee.selector, REQUEST_FEE - 1, REQUEST_FEE));
        consumer.requestRandomness{value: REQUEST_FEE - 1}(ROUND_ID);
    }

    function test_overpayment_reverts() public {
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.IncorrectFee.selector, REQUEST_FEE + 1, REQUEST_FEE));
        consumer.requestRandomness{value: REQUEST_FEE + 1}(ROUND_ID);
    }

    function test_fulfillerReceivesFee() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);
        assertEq(adapter.escrow(_key(address(consumer), ROUND_ID)), REQUEST_FEE);

        address fulfiller = address(0xfeed);
        uint256 balBefore = fulfiller.balance;

        vm.prank(fulfiller);
        adapter.fulfill(address(consumer), ROUND_ID, GAMMA, C, S);

        assertEq(fulfiller.balance - balBefore, REQUEST_FEE);
        assertEq(adapter.escrow(_key(address(consumer), ROUND_ID)), 0);
    }

    function test_zeroFeeDeployment_acceptsZeroValue() public {
        MonadVRFAdapter freeAdapter = new MonadVRFAdapter(address(verifier), PK0, PK1, PK2, PK3, 0);
        MockConsumer freeConsumer = new MockConsumer(address(freeAdapter));

        // No vm.deal, no value forwarded.
        freeConsumer.requestRandomness(ROUND_ID);
        assertTrue(freeAdapter.pendingRequests(adapter.requestKey(address(freeConsumer), ROUND_ID)));

        address fulfiller = address(0xc0de);
        uint256 balBefore = fulfiller.balance;
        vm.prank(fulfiller);
        freeAdapter.fulfill(address(freeConsumer), ROUND_ID, GAMMA, C, S);

        // Free service: no payment.
        assertEq(fulfiller.balance, balBefore);
    }

    function test_zeroFeeDeployment_rejectsValue() public {
        MonadVRFAdapter freeAdapter = new MonadVRFAdapter(address(verifier), PK0, PK1, PK2, PK3, 0);
        MockConsumer freeConsumer = new MockConsumer(address(freeAdapter));
        vm.deal(address(freeConsumer), 1 ether);

        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.IncorrectFee.selector, 1, 0));
        freeConsumer.requestRandomness{value: 1}(ROUND_ID);
    }

    // ── M2 + L1: deploy-time public-key validation; immutable storage ───────

    function test_deployWithIdentityPK_reverts() public {
        // All-zero coordinates = G1 identity. Useless as a verification key.
        vm.expectRevert(MonadVRFAdapter.InvalidPublicKey.selector);
        new MonadVRFAdapter(address(verifier), bytes32(0), bytes32(0), bytes32(0), bytes32(0), REQUEST_FEE);
    }

    function test_deployWithGarbagePK_reverts() public {
        // 128 bytes of 0xff is not a valid encoded G1 point - top 16 bytes of
        // each coordinate slot must be zero (EIP-2537 padding), and the values
        // must reduce to a curve point in the prime-order subgroup.
        bytes32 junk = bytes32(type(uint256).max);
        vm.expectRevert(MonadVRFAdapter.InvalidPublicKey.selector);
        new MonadVRFAdapter(address(verifier), junk, junk, junk, junk, REQUEST_FEE);
    }

    function test_oraclePublicKeyView_returnsOriginalBytes() public view {
        bytes memory got = adapter.oraclePublicKey();
        assertEq(got.length, 128);
        assertEq(keccak256(got), keccak256(PK_BYTES));
    }

    function test_reentrantFulfillFromFulfiller_reverts() public {
        consumer.requestRandomness{value: REQUEST_FEE}(ROUND_ID);

        ReentrantFulfiller attacker = new ReentrantFulfiller(adapter, address(consumer), ROUND_ID, GAMMA, C, S);

        // The fulfill triggers the fee transfer, which lands in attacker.receive(),
        // which tries to re-enter fulfill() for the same (consumer, roundId).
        // The reentrant call must hit the AlreadyFulfilled guard, which causes
        // attacker.receive() to revert, which in turn reverts the outer fulfill
        // (we treat a failed fee transfer as a revert via FeeTransferFailed).
        vm.expectRevert(MonadVRFAdapter.FeeTransferFailed.selector);
        attacker.attack();
    }
}

// Helper for the reentrancy test: triggers fulfill, then on receive() of the
// fee transfer it tries to re-enter fulfill on the same (consumer, roundId).
contract ReentrantFulfiller {
    MonadVRFAdapter public immutable adapter;
    address public immutable consumer;
    bytes32 public immutable roundId;
    bytes public gamma;
    uint256 public c;
    uint256 public s;

    constructor(MonadVRFAdapter a, address consumer_, bytes32 roundId_, bytes memory gamma_, uint256 c_, uint256 s_) {
        adapter = a;
        consumer = consumer_;
        roundId = roundId_;
        gamma = gamma_;
        c = c_;
        s = s_;
    }

    function attack() external {
        adapter.fulfill(consumer, roundId, gamma, c, s);
    }

    receive() external payable {
        // Reentrant attempt - must revert inside the adapter on AlreadyFulfilled,
        // which propagates here as a failed call. We bubble up.
        adapter.fulfill(consumer, roundId, gamma, c, s);
    }
}
