// SPDX-License-Identifier: MIT
pragma solidity ^0.8.28;

import {Test} from "forge-std/Test.sol";
import {MonadVRFVerifier} from "../../src/contracts/MonadVRFVerifier.sol";
import {MonadVRFAdapter}  from "../../src/contracts/MonadVRFAdapter.sol";
import {MockConsumer}     from "./MockConsumer.sol";

// Proof generated by: npx tsx scripts/genProof.ts
// k = 42, roundId = bytes32("round-1"), hash-to-curve via RFC 9380 (@noble/curves)

contract MonadVRFAdapterTest is Test {
    MonadVRFVerifier verifier;
    MonadVRFAdapter  adapter;
    MockConsumer     consumer;

    bytes32 constant ROUND_ID = bytes32("round-1");
    bytes constant PK         = hex"000000000000000000000000000000000ce3b57b791798433fd323753489cac9bca43b98deaafaed91f4cb010730ae1e38b186ccd37a09b8aed62ce23b699c4800000000000000000000000000000000008c346228e4482ec20a2bf7d5a2fe74ebf3c79b912d1b0ba977a873b66f7a9b8b42585a78c0c21d66da6a15767efdb1";
    bytes constant GAMMA      = hex"000000000000000000000000000000000bb381154dc86a2b91eb3710aa412ea071e91d5122c976b0e8775474f5c5911667253293f9cdcdd05887adc908a5f4d500000000000000000000000000000000016c6b67b701a7ae42421582570c9fedef994318c7656659169985792799f39a3c2ed6b8285d6312e5179084713314da";
    uint256 constant C        = 0x5973b13f00290106fe0be3dff5d921507ddb1ee0223870bb74f58fb9863f8662;
    uint256 constant S        = 0x0b61101267947db0fe93d38a4cddcecb3c7988a9d4940f280ab23c1f9785ef59;
    bytes32 constant BETA     = 0xcd851f1243dc4ae51c01c5688fd087556f5a1b44e65bdd4ac53408f89f513abd;

    function setUp() public {
        verifier = new MonadVRFVerifier();
        adapter  = new MonadVRFAdapter(address(verifier), PK);
        consumer = new MockConsumer(address(adapter));
    }

    function test_fullFlow() public {
        consumer.requestRandomness(ROUND_ID);

        assertEq(adapter.pendingRequests(ROUND_ID), address(consumer));
        assertEq(adapter.fulfilled(ROUND_ID), false);

        vm.expectEmit(true, false, false, true);
        emit MonadVRFAdapter.RandomnessFulfilled(ROUND_ID, BETA);

        adapter.fulfill(ROUND_ID, GAMMA, C, S);

        assertEq(consumer.lastRoundId(), ROUND_ID);
        assertEq(consumer.lastBeta(),    BETA);
        assertEq(adapter.fulfilled(ROUND_ID), true);
        assertEq(adapter.pendingRequests(ROUND_ID), address(0));
    }

    function test_anyoneCanFulfill() public {
        consumer.requestRandomness(ROUND_ID);
        vm.prank(address(0xdead));
        adapter.fulfill(ROUND_ID, GAMMA, C, S);
        assertEq(consumer.lastBeta(), BETA);
    }

    function test_duplicateRequest_reverts() public {
        consumer.requestRandomness(ROUND_ID);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyRequested.selector, ROUND_ID));
        consumer.requestRandomness(ROUND_ID);
    }

    function test_requestAfterFulfill_reverts() public {
        consumer.requestRandomness(ROUND_ID);
        adapter.fulfill(ROUND_ID, GAMMA, C, S);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyFulfilled.selector, ROUND_ID));
        consumer.requestRandomness(ROUND_ID);
    }

    function test_fulfillWithoutRequest_reverts() public {
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.NoPendingRequest.selector, ROUND_ID));
        adapter.fulfill(ROUND_ID, GAMMA, C, S);
    }

    function test_replayFulfill_reverts() public {
        consumer.requestRandomness(ROUND_ID);
        adapter.fulfill(ROUND_ID, GAMMA, C, S);
        vm.expectRevert(abi.encodeWithSelector(MonadVRFAdapter.AlreadyFulfilled.selector, ROUND_ID));
        adapter.fulfill(ROUND_ID, GAMMA, C, S);
    }

    function test_invalidProof_reverts() public {
        consumer.requestRandomness(ROUND_ID);
        vm.expectRevert(MonadVRFAdapter.InvalidProof.selector);
        adapter.fulfill(ROUND_ID, GAMMA, C + 1, S);
    }
}
