// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {MonadVRFVerifier} from "../../src/contracts/MonadVRFVerifier.sol";

// Proof generated by scripts/genProof.ts with k=42, roundId=bytes32("round-1")
// H is now computed on-chain from ROUND_ID - not a test constant.

contract MonadVRFVerifierTest is Test {
    MonadVRFVerifier verifier;

    bytes32 constant ROUND_ID = bytes32("round-1");
    bytes constant PK =
        hex"000000000000000000000000000000000ce3b57b791798433fd323753489cac9bca43b98deaafaed91f4cb010730ae1e38b186ccd37a09b8aed62ce23b699c4800000000000000000000000000000000008c346228e4482ec20a2bf7d5a2fe74ebf3c79b912d1b0ba977a873b66f7a9b8b42585a78c0c21d66da6a15767efdb1";
    bytes constant GAMMA =
        hex"00000000000000000000000000000000018e0f3034f6ef0571c5ac89293cf142b55e4e7fd65f0dc685ef1a44f0c4aff3283379067aa154eeb3d6826441e1d3fd0000000000000000000000000000000010a62f42d0c5e3a7529af72f239e74c43163988e6bfa4a014050ffe481ff33f47aefefeb6a1d7575ced01fd0b322f739";
    uint256 constant C = 0x4d98ac45cf18281cc1169304ce44e7555eb5e62df1abfc9e263e75f68d842911;
    uint256 constant S = 0x14abc8bd327689055b443be8336b9230808fd25d8742e8bb88a129615f85ec46;

    function setUp() public {
        verifier = new MonadVRFVerifier();
    }

    function test_validProofVerifies() public view {
        assertTrue(verifier.verifyProof(PK, ROUND_ID, GAMMA, C, S));
    }

    function test_wrongC_fails() public view {
        assertFalse(verifier.verifyProof(PK, ROUND_ID, GAMMA, C + 1, S));
    }

    function test_wrongS_fails() public view {
        assertFalse(verifier.verifyProof(PK, ROUND_ID, GAMMA, C, S + 1));
    }

    function test_wrongGamma_fails() public view {
        bytes memory fakeGamma = abi.encodePacked(GAMMA);
        fakeGamma[127] ^= 0xff;
        assertFalse(verifier.verifyProof(PK, ROUND_ID, fakeGamma, C, S));
    }

    function test_wrongPublicKey_fails() public view {
        bytes memory fakeKey = abi.encodePacked(PK);
        fakeKey[127] ^= 0xff;
        assertFalse(verifier.verifyProof(fakeKey, ROUND_ID, GAMMA, C, S));
    }

    function test_wrongRoundId_fails() public view {
        assertFalse(verifier.verifyProof(PK, bytes32("round-2"), GAMMA, C, S));
    }

    function test_shortInput_fails() public view {
        assertFalse(verifier.verifyProof(hex"deadbeef", ROUND_ID, GAMMA, C, S));
    }
}
