// SPDX-License-Identifier: MIT
pragma solidity 0.8.28;

import {Test} from "forge-std/Test.sol";
import {MonadVRFVerifier} from "../../src/contracts/MonadVRFVerifier.sol";

// Proof generated by scripts/genProof.ts with k=42, roundId=bytes32("round-1")
// H is now computed on-chain from ROUND_ID - not a test constant.

contract MonadVRFVerifierTest is Test {
    MonadVRFVerifier verifier;

    bytes32 constant ROUND_ID = bytes32("round-1");
    bytes constant PK =
        hex"000000000000000000000000000000000ce3b57b791798433fd323753489cac9bca43b98deaafaed91f4cb010730ae1e38b186ccd37a09b8aed62ce23b699c4800000000000000000000000000000000008c346228e4482ec20a2bf7d5a2fe74ebf3c79b912d1b0ba977a873b66f7a9b8b42585a78c0c21d66da6a15767efdb1";
    bytes constant GAMMA =
        hex"000000000000000000000000000000000bb381154dc86a2b91eb3710aa412ea071e91d5122c976b0e8775474f5c5911667253293f9cdcdd05887adc908a5f4d500000000000000000000000000000000016c6b67b701a7ae42421582570c9fedef994318c7656659169985792799f39a3c2ed6b8285d6312e5179084713314da";
    uint256 constant C = 0x5973b13f00290106fe0be3dff5d921507ddb1ee0223870bb74f58fb9863f8662;
    uint256 constant S = 0x0b61101267947db0fe93d38a4cddcecb3c7988a9d4940f280ab23c1f9785ef59;

    function setUp() public {
        verifier = new MonadVRFVerifier();
    }

    function test_validProofVerifies() public view {
        assertTrue(verifier.verifyProof(PK, ROUND_ID, GAMMA, C, S));
    }

    function test_wrongC_fails() public view {
        assertFalse(verifier.verifyProof(PK, ROUND_ID, GAMMA, C + 1, S));
    }

    function test_wrongS_fails() public view {
        assertFalse(verifier.verifyProof(PK, ROUND_ID, GAMMA, C, S + 1));
    }

    function test_wrongGamma_fails() public view {
        bytes memory fakeGamma = abi.encodePacked(GAMMA);
        fakeGamma[127] ^= 0xff;
        assertFalse(verifier.verifyProof(PK, ROUND_ID, fakeGamma, C, S));
    }

    function test_wrongPublicKey_fails() public view {
        bytes memory fakeKey = abi.encodePacked(PK);
        fakeKey[127] ^= 0xff;
        assertFalse(verifier.verifyProof(fakeKey, ROUND_ID, GAMMA, C, S));
    }

    function test_wrongRoundId_fails() public view {
        assertFalse(verifier.verifyProof(PK, bytes32("round-2"), GAMMA, C, S));
    }

    function test_shortInput_fails() public view {
        assertFalse(verifier.verifyProof(hex"deadbeef", ROUND_ID, GAMMA, C, S));
    }
}
