[profile.default]
src = "src/contracts"
out = "out"
test = "test/contracts"
libs = ["lib"]
solc = "0.8.28"
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
monad_testnet = "https://testnet-rpc.monad.xyz"

[etherscan]
monad_testnet = { key = "${MONAD_ETHERSCAN_API_KEY}", url = "https://testnet.monadexplorer.com/api" }
